# This is a basic workflow to help you get started with Actions
name: windows-build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DJSTAR_COMPUTED_GOTOS=OFF -DCMAKE_INSTALL_PREFIX=release/jstar
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: build
      run: |
        cd build
        msbuild -t:Build -p:Configuration=Release -m jstar.sln
    - name: package binaries
      run: |
        cd build
        mkdir -p release/jstar
        msbuild -p:Configuration=Release INSTALL.vcxproj
    - name: upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: jstar-x64-windows
        path: build/release/jstar
        
