// WARNING: this is a file generated automatically by the build process from
// "/home/fabrizio/Workspace/c/blang/src/vm/builtin/math.jsr". Do not modify.
const char *math_jsr =
"native abs(x)\n"
"native acos(x)\n"
"native asin(x)\n"
"native atan(x)\n"
"native atan2(y, x)\n"
"native ceil(x)\n"
"native cos(x)\n"
"native cosh(x)\n"
"native deg(x)\n"
"native exp(x)\n"
"native floor(x)\n"
"native frexp(x)\n"
"native ldexp(x, exp)\n"
"native log(x)\n"
"native log10(x)\n"
"native max(x, y)\n"
"native min(x, y)\n"
"native rad(x)\n"
"native sin(x)\n"
"native sinh(x)\n"
"native sqrt(x)\n"
"native tan(x)\n"
"native tanh(x)\n"
"native modf(x)\n"
"native random()\n"
"native seed(s)\n"
"fun randint(a, b=null)\n"
"    if !isInt(a) or (b and !isInt(b)) then\n"
"        raise InvalidArgException(\"a and b must be integers\")\n"
"    end\n"
"    if b == null then\n"
"        a, b = 0, a\n"
"    end\n"
"    if a >= b then \n"
"        raise InvalidArgException(\"a must be < b\") \n"
"    end\n"
"    return int(a + random() * (b - a + 1))\n"
"end\n"
"begin\n"
"    native init()\n"
"    init()\n"
"end\n"
;