// WARNING: this is a file generated automatically by the build process from
// "/home/fabrizio/Workspace/c/blang/src/vm/builtin/re.jsr". Do not modify.
const char *re_jsr =
"class RegexException : Exception end\n"
"native match(str, regex, off=0)\n"
"native find(str, regex, off=0)\n"
"native gmatch(str, regex)\n"
"native gsub(str, regex, sub, num=0)\n"
"fun gfind(s, r)\n"
"    var off, endl = 0, null\n"
"    class GfindIter\n"
"        fun __iter__(_)\n"
"            var res = find(s, r, off)\n"
"            if !res then \n"
"                return null \n"
"            end\n"
"            \n"
"            var b, e = res\n"
"            while e == endl and e - b == 0 do\n"
"                if !(res = find(s, r, off += 1)) then\n"
"                    return null\n"
"                end\n"
"                b, e = res\n"
"            end\n"
"            off = endl = e\n"
"            var nres = #res\n"
"            if nres == 2 then\n"
"                return s.substr(b, e)\n"
"            elif nres == 3 then\n"
"                return res[2]\n"
"            else\n"
"                return res.sub(2, nres)\n"
"            end\n"
"        end\n"
"        fun __next__(match)\n"
"            return match\n"
"        end\n"
"    end\n"
"    return GfindIter()\n"
"end\n"
;